# Generated by Django 4.2.21 on 2025-06-04 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filepath', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='uploads/')),
                ('json_data', models.JSONField(blank=True, null=True)),
                ('entry_date', models.DateField(default=django.utils.timezone.now)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
