# Generated by Django 4.2.21 on 2025-06-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageApp1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='html_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
