# Generated by Django 4.2.21 on 2025-06-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageApp1', '0002_document_html_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='reimbursement_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
