# Generated by Django 4.2.21 on 2025-06-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageApp1', '0003_document_reimbursement_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='reimbursement_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
