# Generated by Django 4.2.21 on 2025-06-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageApp1', '0004_alter_document_reimbursement_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='reimbursement_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
