# Generated by Django 4.2.21 on 2025-06-20 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ImageApp1', '0005_alter_document_reimbursement_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='reimbursement_data',
            new_name='document_type',
        ),
    ]
