# Generated by Django 4.2.21 on 2025-06-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageApp1', '0006_rename_reimbursement_data_document_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='input_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='output_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
