# Generated by Django 4.2.21 on 2025-06-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageApp1', '0007_document_input_token_document_output_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='input_token',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='output_token',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
